import { NextRequest, NextResponse } from 'next/server';
import { getInstallationChangelog } from '@/lib/winget-api';

export const runtime = 'edge';

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const packageId = searchParams.get('id');
    const version = searchParams.get('version');

    if (!packageId) {
      return NextResponse.json(
        { error: 'Package ID parameter "id" is required' },
        { status: 400 }
      );
    }

    const changelog = await getInstallationChangelog(packageId, version || undefined);

    if (!changelog) {
      return NextResponse.json(
        {
          error: 'No installation changelog found',
          message: 'This package has not been scanned yet. Installation changelog data is generated by the scan-apps workflow.'
        },
        { status: 404 }
      );
    }

    return NextResponse.json({
      changelog,
      summary: {
        filesAdded: changelog.file_changes?.file_count || 0,
        shortcutsCreated: changelog.shortcuts_created?.length || 0,
        servicesCreated: changelog.services_created?.length || 0,
        registryEntriesAdded: changelog.registry_changes?.added?.length || 0,
        installedSizeMB: changelog.installed_size_bytes
          ? Math.round(changelog.installed_size_bytes / 1024 / 1024 * 100) / 100
          : null,
      }
    });
  } catch {
    return NextResponse.json(
      { error: 'Failed to fetch installation changelog' },
      { status: 500 }
    );
  }
}
