import {
  generateDetectionRules,
  generateUninstallCommand,
} from '@/lib/detection-rules';
import { reconcileManagedMarkerDetectionRules } from '@/lib/registry-marker';
import type { DetectionRule } from '@/types/intune';
import type { DeploymentConfig } from '@/types/update-policies';
import type { NormalizedInstaller, WingetInstallerType, WingetScope } from '@/types/winget';

export interface CurrentPackageMetadata {
  wingetId: string;
  version: string;
  displayName: string;
  installerUrl: string;
  installerSha256: string;
  installerType: string;
  installScope?: WingetScope;
}

export interface LegacyPackageUpgradeResult {
  config: DeploymentConfig;
  changed: boolean;
  upgradedUninstallCommand: boolean;
  upgradedDetectionRules: boolean;
  reconciledManagedDetectionRules: boolean;
}

const MSI_PLACEHOLDER = /\{(?:PRODUCT_CODE|PRODUCTCODE|PRODUCT)\}/i;
const MSI_IDENTITY_SENTINEL = /^\s*MSI_UNINSTALL_IDENTITY_REQUIRED\s*$/i;
const KNOWN_INSTALLER_TYPES = new Set<WingetInstallerType>([
  'msix',
  'msi',
  'appx',
  'exe',
  'zip',
  'inno',
  'nullsoft',
  'wix',
  'burn',
  'pwa',
  'portable',
]);

function normalizeInstallerType(value: string): WingetInstallerType {
  const normalized = value.trim().toLowerCase() as WingetInstallerType;
  return KNOWN_INSTALLER_TYPES.has(normalized) ? normalized : 'exe';
}

function normalizeScope(value?: string): WingetScope {
  return value?.trim().toLowerCase() === 'user' ? 'user' : 'machine';
}

function legacyFolderName(displayName: string): string {
  const value = displayName.replace(/[<>:"/\\|?*]/g, '').trim();
  return (value.length > 64 ? value.slice(0, 64).trim() : value) || 'Application';
}

function isLegacyGeneratedFolderRule(
  detectionRules: DetectionRule[],
  displayName: string,
  architecture: string,
  scope: WingetScope
): boolean {
  if (detectionRules.length !== 1) return false;

  const rule = detectionRules[0] as unknown as Record<string, unknown>;
  const allowedKeys = new Set([
    'type',
    'path',
    'fileOrFolderName',
    'detectionType',
    'check32BitOn64System',
  ]);
  if (Object.keys(rule).some((key) => !allowedKeys.has(key))) return false;

  const expectedPath = scope === 'user'
    ? '%LOCALAPPDATA%\\Programs'
    : architecture.trim().toLowerCase() === 'x86'
      ? '%ProgramFiles(x86)%'
      : '%ProgramFiles%';

  return (
    rule.type === 'file' &&
    rule.path === expectedPath &&
    rule.fileOrFolderName === legacyFolderName(displayName) &&
    rule.detectionType === 'exists' &&
    rule.check32BitOn64System === (architecture.trim().toLowerCase() === 'x86')
  );
}

function sameRules(left: DetectionRule[], right: DetectionRule[]): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function cloneRules(rules: DetectionRule[]): DetectionRule[] {
  return rules.map((rule) => ({ ...rule }));
}

/**
 * Upgrade only defaults emitted by older IntuneGet releases.
 *
 * Old MSI profiles could contain a literal {PRODUCT_CODE} token and the old
 * generic folder-existence rule. Both values were generated by IntuneGet,
 * not selected by the customer. Modern PSADT packages capture the installed
 * uninstall registration and write an owned version marker, so migrate those
 * exact legacy shapes while preserving every custom rule and command.
 */
export function upgradeLegacyPackageDefaults(
  current: DeploymentConfig,
  metadata: CurrentPackageMetadata
): LegacyPackageUpgradeResult {
  const config: DeploymentConfig = {
    ...current,
    detectionRules: [...(current.detectionRules || [])],
    psadtConfig: current.psadtConfig
      ? {
          ...current.psadtConfig,
          detectionRules: [...(current.psadtConfig.detectionRules || [])],
        }
      : undefined,
  };
  const installerType = normalizeInstallerType(
    metadata.installerType || current.installerType || 'exe'
  );
  const storedScope = normalizeScope(current.installScope);
  const scope = normalizeScope(metadata.installScope || current.installScope);
  const displayName = current.displayName || metadata.displayName;
  const installer: NormalizedInstaller = {
    architecture: (current.architecture || 'x64').toLowerCase() as NormalizedInstaller['architecture'],
    url: metadata.installerUrl,
    sha256: metadata.installerSha256,
    type: installerType,
    scope,
  };

  let upgradedUninstallCommand = false;
  let upgradedDetectionRules = false;
  let reconciledManagedDetectionRules = false;

  const repairLegacyMsiCommand = (value: string): string => {
    if (!MSI_PLACEHOLDER.test(value) && !MSI_IDENTITY_SENTINEL.test(value)) {
      return value;
    }
    // The stored command proves that the old package was MSI-backed even if
    // the vendor changed installer technology in the current release. Force
    // the modern no-ProductCode MSI path, which resolves the exact ARP entry
    // created during installation instead of executing a literal token.
    return generateUninstallCommand({ ...installer, type: 'msi', productCode: undefined }, displayName);
  };

  const repairedUninstallCommand = repairLegacyMsiCommand(config.uninstallCommand || '');
  if (repairedUninstallCommand !== config.uninstallCommand) {
    config.uninstallCommand = repairedUninstallCommand;
    upgradedUninstallCommand = true;
  }

  if (config.psadtConfig?.uninstallCommand) {
    const repairedOverride = repairLegacyMsiCommand(config.psadtConfig.uninstallCommand);
    if (repairedOverride !== config.psadtConfig.uninstallCommand) {
      config.psadtConfig.uninstallCommand = repairedOverride;
      upgradedUninstallCommand = true;
    }
  }

  const reconcileRules = (rules: DetectionRule[]): DetectionRule[] => {
    let nextRules = rules;
    if (
      isLegacyGeneratedFolderRule(
        rules,
        displayName,
        current.architecture || 'x64',
        storedScope
      ) &&
      installerType !== 'msix' &&
      installerType !== 'appx'
    ) {
      nextRules = generateDetectionRules(
        installer,
        displayName,
        metadata.wingetId,
        metadata.version,
        config.psadtConfig?.registryMarkerPath
      );
      upgradedDetectionRules = true;
    }

    const reconciled = reconcileManagedMarkerDetectionRules({
      detectionRules: nextRules,
      wingetId: metadata.wingetId,
      version: metadata.version,
      installScope: scope,
      markerPath: config.psadtConfig?.registryMarkerPath,
    });
    if (!sameRules(nextRules, reconciled)) {
      reconciledManagedDetectionRules = true;
    }
    return cloneRules(reconciled);
  };

  config.detectionRules = reconcileRules(config.detectionRules);
  if (config.psadtConfig) {
    config.psadtConfig.detectionRules = reconcileRules(
      config.psadtConfig.detectionRules || []
    );
  }

  return {
    config,
    changed:
      upgradedUninstallCommand ||
      upgradedDetectionRules ||
      reconciledManagedDetectionRules,
    upgradedUninstallCommand,
    upgradedDetectionRules,
    reconciledManagedDetectionRules,
  };
}
